export const optionSector = [
  { value: "Automotriz", label: "Automotriz" },
  { value: "Metalúrgico", label: "Metalúrgico" },
  { value: "Ganadería", label: "Ganadería" },
  { value: "Agricultura", label: "Agricultura" },
  { value: "Plásticos", label: "Plásticos" },
  { value: "Química", label: "Química" },
  { value: "Biotecnología", label: "Biotecnología" },
  { value: "Logística", label: "Logística" },
  { value: "Acopio", label: "Acopio" },
  { value: "Distribución", label: "Distribución" },
  { value: "Exportación", label: "Exportación" },
  { value: "Construcción", label: "Construcción" },
  { value: "Real Estate", label: "Real Estate" },
  { value: "Servicios Informáticos", label: "Servicios Informáticos" },
  { value: "Servicios Legales", label: "Servicios Legales" },
  { value: "Servicios Financieros", label: "Servicios Financieros" },
  { value: "Alimentos", label: "Alimentos" },
  { value: "Textiles", label: "Textiles" },
  { value: "Otros", label: "Otros" },
];
